/**
 * Encode the Bible data using UTF-16 and Base64.
 * @param {Array} bibleData - Array of books with chapters and verses.
 * @returns {Object} Encoded Bible data with Base64 strings.
 */
const encodeBibleDataUTF16Base64(bibleData) {
  const encodedData = {};
  bibleData.forEach(bookEntry => {
    const bookName = bookEntry.book;
    const chapters = bookEntry.chapters.map(chapter => String.fromCharCode(parseInt(chapter.verses))).join('');
    const utf16Bytes = new Uint16Array(chapters.length);
    for (let i = 0; i < chapters.length; i++) {
      utf16Bytes[i] = chapters.charCodeAt(i);
    }
    const utf16Array = new Uint8Array(utf16Bytes.buffer);
    const base64Encoded = btoa(String.fromCharCode.apply(null, utf16Array)).replace(/=+$/, '');
    encodedData[bookName] = base64Encoded;
  });
  return encodedData;
}

/**
 * Decode a Base64 string to a UTF-16LE string.
 * @param {String} b64 - Base64 encoded string.
 * @returns {String} Decoded UTF-16LE string.
 */
const decodeBase64UTF16LE = b64 => {
  const bin = atob(b64.padEnd(b64.length + (4 - b64.length % 4) % 4, '='));
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder('utf-16le').decode(bytes);
};

/**
 * Get the number of chapters in a book.
 * @param {Object} data - Encoded Bible data.
 * @param {String} book - Book name.
 * @returns {Number} Number of chapters in the book.
 */
const getNumChapters = (data, book) => data[book] ? decodeBase64UTF16LE(data[book]).length : 0;

/**
 * Get the number of verses in a specific chapter.
 * @param {Object} data - Encoded Bible data.
 * @param {String} book - Book name.
 * @param {Number} chapter - Chapter number.
 * @returns {Number} Number of verses in the chapter.
 */
const getNumVerses = (data, book, chapter) => {
  const chapters = data[book] ? decodeBase64UTF16LE(data[book]) : '';
  return chapters.length >= chapter ? chapters.charCodeAt(chapter - 1) : 0;
};

// Encoded Bible data as generated by encodeBibleDataUTF16Base64
const books = {
  "Genesis": "HwAZABgAGgAgABYAGAAWAB0AIAAgABQAEgAYABUAEAAbACEAJgASACIAGAAUAEMAIgAjAC4AFgAjACsANwAgABQAHwAdACsAJAAeABcAFwA5ACYAIgAiABwAIgAfABYAIQAaAA",
  "Exodus": "FgAZABYAHwAXAB4AGQAgACMAHQAKADMAFgAfABsAJAAQABsAGQAaACQAHwAhABIAKAAlABUAKwAuACYAEgAjABcAIwAjACYAHQAfACsAJgA",
  "Leviticus": "EQAQABEAIwATAB4AJgAkABgAFAAvAAgAOwA5ACEAIgAQAB4AJQAbABgAIQAsABcANwAuACIA",
  "Numbers": "NgAiADMAMQAfABsAWQAaABcAJAAjABAAIQAtACkAMgANACAAFgAdACMAKQAeABkAEgBBABcAHwAoABAANgAqADgAHQAiAA0A",
  "Deuteronomy": "LgAlAB0AMQAhABkAGgAUAB0AFgAgACAAEgAdABcAFgAUABYAFQAUABcAHgAZABYAEwATABoARAAdABQAHgA0AB0ADAA",
  "Joshua": "EgAYABEAGAAPABsAGgAjABsAKwAXABgAIQAPAD8ACgASABwAMwAJAC0AIgAQACEA",
  "Judges": "JAAXAB8AGAAfACgAGQAjADkAEgAoAA8AGQAUABQAHwANAB8AHgAwABkA",
  "Ruth": "FgAXABIAFgA",
  "1 Samuel": "HAAkABUAFgAMABUAEQAWABsAGwAPABkAFwA0ACMAFwA6AB4AGAAqAA8AFwAdABYALAAZAAwAGQALAB8ADQA",
  "2 Samuel": "GwAgACcADAAZABcAHQASAA0AEwAbAB8AJwAhACUAFwAdACEAKwAaABYAMwAnABkA",
  "1 Kings": "NQAuABwAIgASACYAMwBCABwAHQArACEAIgAfACIAIgAYAC4AFQArAB0ANQA",
  "2 Kings": "EgAZABsALAAbACEAFAAdACUAJAAVABUAGQAdACYAFAApACUAJQAVABoAFAAlABQAHgA",
  "1 Chronicles": "NgA3ABgAKwAaAFEAKAAoACwADgAvACgADgARAB0AKwAbABEAEwAIAB4AEwAgAB8AHwAgACIAFQAeAA",
  "2 Chronicles": "EQASABEAFgAOACoAFgASAB8AEwAXABAAFgAPABMADgATACIACwAlABQADAAVABsAHAAXAAkAGwAkABsAFQAhABkAIQAbABcA",
  "Ezra": "CwBGAA0AGAARABYAHAAkAA8ALAA",
  "Nehemiah": "CwAUACAAFwATABMASQASACYAJwAkAC8AHwA",
  "Esther": "FgAXAA8AEQAOAA4ACgARACAAAwA",
  "Job": "FgANABoAFQAbAB4AFQAWACMAFgAUABkAHAAWACMAFgAQABUAHQAdACIAHgARABkABgAOABcAHAAZAB8AKAAWACEAJQAQACEAGAApAB4AGAAiABEA",
  "Psalm": "BgAMAAgACAAMAAoAEQAJABQAEgAHAAgABgAHAAUACwAPADIADgAJAA0AHwAGAAoAFgAMAA4ACQALAAwAGAALABYAFgAcAAwAKAAWAA0AEQANAAsABQAaABEACwAJAA4AFAAXABMACQAGAAcAFwANAAsACwARAAwACAAMAAsACgANABQABwAjACQABQAYABQAHAAXAAoADAAUAEgADQATABAACAASAAwADQARAAcAEgA0ABEAEAAPAAUAFwALAA0ADAAJAAkABQAIABwAFgAjAC0AMAArAA0AHwAHAAoACgAJAAgAEgATAAIAHQCwAAcACAAJAAQACAAFAAYABQAGAAgACAADABIAAwADABUAGgAJAAgAGAANAAoABwAMAA8AFQAKABQADgAJAAYA",
  "Proverbs": "IQAWACMAGwAXACMAGwAkABIAIAAfABwAGQAjACEAIQAcABgAHQAeAB8AHQAjACIAHAAcABsAHAAbACEAHwA",
  "Ecclesiastes": "EgAaABYAEAAUAAwAHQARABIAFAAKAA4A",
  "Song of Solomon": "EQARAAsAEAAQAA0ADQAOAA",
  "Isaiah": "HwAWABoABgAeAA0AGQAWABUAIgAQAAYAFgAgAAkADgAOAAcAGQAGABEAGQASABcADAAVAA0AHQAYACEACQAUABgAEQAKABYAJgAWAAgAHwAdABkAHAAcABkADQAPABYAGgALABcADwAMABEADQAMABUADgAVABYACwAMABMADAAZABgA",
  "Jeremiah": "EwAlABkAHwAfAB4AIgAWABoAGQAXABEAGwAWABUAFQAbABcADwASAA4AHgAoAAoAJgAYABYAEQAgABgAKAAsABoAFgATACAAFQAcABIAEAASABYADQAeAAUAHAAHAC8AJwAuAEAAIgA",
  "Lamentations": "FgAWAEIAFgAWAA",
  "Ezekiel": "HAAKABsAEQARAA4AGwASAAsAFgAZABwAFwAXAAgAPwAYACAADgAxACAAHwAxABsAEQAVACQAGgAVABoAEgAgACEAHwAPACYAHAAXAB0AMQAaABQAGwAfABkAGAAXACMA",
  "Daniel": "FQAxAB4AJQAfABwAHAAbABsAFQAtAA0A",
  "Hosea": "CwAXAAUAEwAPAAsAEAAOABEADwAMAA4AEAAJAA",
  "Joel": "FAAgABUA",
  "Amos": "DwAQAA8ADQAbAA4AEQAOAA8A",
  "Obadiah": "FQA",
  "Jonah": "EQAKAAoACwA",
  "Micah": "EAANAAwADQAPABAAFAA",
  "Nahum": "DwANABMA",
  "Habakkuk": "EQAUABMA",
  "Zephaniah": "EgAPABQA",
  "Haggai": "DwAXAA",
  "Zechariah": "FQANAAoADgALAA8ADgAXABEADAARAA4ACQAVAA",
  "Malachi": "DgARABIABgA",
  "Matthew": "GQAXABEAGQAwACIAHQAiACYAKgAeADIAOgAkACcAHAAbACMAHgAiAC4ALgAnADMALgBLAEIAFAA",
  "Mark": "LQAcACMAKQArADgAJQAmADIANAAhACwAJQBIAC8AFAA",
  "Luke": "UAA0ACYALAAnADEAMgA4AD4AKgA2ADsAIwAjACAAHwAlACsAMAAvACYARwA4ADUA",
  "John": "MwAZACQANgAvAEcANQA7ACkAKgA5ADIAJgAfABsAIQAaACgAKgAfABkA",
  "Acts": "GgAvABoAJQAqAA8APAAoACsAMAAeABkANAAcACkAKAAiABwAKQAmACgAHgAjABsAGwAgACwAHwA",
  "Romans": "IAAdAB8AGQAVABcAGQAnACEAFQAkABUADgAXACEAGwA",
  "1 Corinthians": "HwAQABcAFQANABQAKAANABsAIQAiAB8ADQAoADoAGAA",
  "2 Corinthians": "GAARABIAEgAVABIAEAAYAA8AEgAhABUADgA",
  "Galatians": "GAAVAB0AHwAaABIA",
  "Ephesians": "FwAWABUAIAAhABgA",
  "Philippians": "HgAeABUAFwA",
  "Colossians": "HQAXABkAEgA",
  "1 Thessalonians": "CgAUAA0AEgAcAA",
  "2 Thessalonians": "DAARABIA",
  "1 Timothy": "FAAPABAAEAAZABUA",
  "2 Timothy": "EgAaABEAFgA",
  "Titus": "EAAPAA8A",
  "Philemon": "GQA",
  "Hebrews": "DgASABMAEAAOABQAHAANABwAJwAoAB0AGQA",
  "James": "GwAaABIAEQAUAA",
  "1 Peter": "GQAZABYAEwAOAA",
  "2 Peter": "FQAWABIA",
  "1 John": "CgAdABgAFQAVAA",
  "2 John": "DQA",
  "3 John": "DgA",
  "Jude": "GQA",
  "Revelation": "FAAdABYACwAOABEAEQANABUACwATABEAEgAUAAgAFQASABgAFQAPABsAFQA"
};